// Approval Workflow
// =================
// State machine for task automation. Sensitive actions (sending real emails,
// placing supplier orders, changing staff roster, running real campaigns,
// replying to customers) MUST pass through human approval before execution.
// Non-sensitive actions (generating drafts, briefings, checklists, logs) are
// auto-approved. Every state transition is audit-logged.

export type TaskCategory =
  | "briefing" // manager briefing generation (auto-approved)
  | "checklist" // opening / pre-peak / closing checklist (auto-approved)
  | "staff-message" // draft message to staff (auto-approved draft, send needs approval)
  | "manager-email" // draft email to area manager (auto-approved draft, send needs approval)
  | "supplier-order" // supplier order DRAFT (approval required to actually order)
  | "incident-report" // incident report (auto-approved, share needs approval)
  | "campaign" // campaign draft (approval required to run)
  | "customer-reply" // customer reply draft (approval required to send)
  | "staff-roster-change" // roster change draft (approval required)
  | "end-of-day-summary"; // EOD summary (auto-approved)

export type TaskStatus =
  | "draft" // generated, awaiting review
  | "pending-approval" // submitted for approval
  | "approved" // approved, ready to execute/export
  | "rejected" // rejected by manager
  | "executed" // executed (exported / sent / applied)
  | "expired"; // stale, auto-expired

export interface ApprovalRequirement {
  requiresApproval: boolean;
  reason: string;
  approverRole: "store-manager" | "area-manager";
  riskLevel: "low" | "medium" | "high";
}

export interface AutomationTask {
  id: string;
  storeId: string;
  storeName: string;
  category: TaskCategory;
  title: string;
  description: string;
  content: string; // the draft body (email text, checklist, order details, etc.)
  status: TaskStatus;
  approval: ApprovalRequirement;
  generatedAt: string;
  submittedAt?: string;
  decidedAt?: string;
  decidedBy?: string;
  executedAt?: string;
  reason: string; // why the task was generated
  dataUsed: string[]; // list of data sources / signals used
  confidence: number;
  riskNote: string;
  auditLog: { at: string; action: string; by?: string; note?: string }[];
}

let _seq = 0;
function tid(): string {
  _seq += 1;
  return `task-${Date.now().toString(36)}-${_seq.toString(36)}`;
}

/** Determine approval requirements for a category. */
export function approvalFor(category: TaskCategory): ApprovalRequirement {
  switch (category) {
    case "briefing":
    case "checklist":
    case "incident-report":
    case "end-of-day-summary":
      return { requiresApproval: false, reason: "Internal draft — no external impact.", approverRole: "store-manager", riskLevel: "low" };
    case "staff-message":
      return { requiresApproval: true, reason: "Sends a real message to staff — manager must confirm wording.", approverRole: "store-manager", riskLevel: "medium" };
    case "manager-email":
      return { requiresApproval: true, reason: "Sends a real email to area manager — manager must confirm.", approverRole: "store-manager", riskLevel: "medium" };
    case "supplier-order":
      return { requiresApproval: true, reason: "Commits a purchase order — financial impact.", approverRole: "store-manager", riskLevel: "high" };
    case "campaign":
      return { requiresApproval: true, reason: "Launches a real campaign — spend + customer impact.", approverRole: "area-manager", riskLevel: "high" };
    case "customer-reply":
      return { requiresApproval: true, reason: "Sends a real reply to a customer — brand impact.", approverRole: "store-manager", riskLevel: "high" };
    case "staff-roster-change":
      return { requiresApproval: true, reason: "Changes staff roster — labour impact.", approverRole: "store-manager", riskLevel: "high" };
    default:
      return { requiresApproval: true, reason: "Default: require approval.", approverRole: "store-manager", riskLevel: "medium" };
  }
}

/** Create a new task in draft state. */
export function createTask(args: {
  storeId: string;
  storeName: string;
  category: TaskCategory;
  title: string;
  description: string;
  content: string;
  reason: string;
  dataUsed: string[];
  confidence: number;
  riskNote: string;
}): AutomationTask {
  const approval = approvalFor(args.category);
  const now = new Date().toISOString();
  return {
    id: tid(),
    storeId: args.storeId,
    storeName: args.storeName,
    category: args.category,
    title: args.title,
    description: args.description,
    content: args.content,
    status: "draft",
    approval,
    generatedAt: now,
    reason: args.reason,
    dataUsed: args.dataUsed,
    confidence: args.confidence,
    riskNote: args.riskNote,
    auditLog: [{ at: now, action: "created", note: "Generated by Task Automation Agent" }],
  };
}

/** Submit a draft for approval. */
export function submitForApproval(task: AutomationTask, by?: string): AutomationTask {
  if (!task.approval.requiresApproval) {
    // Auto-approve non-sensitive tasks.
    const now = new Date().toISOString();
    return {
      ...task,
      status: "approved",
      submittedAt: now,
      decidedAt: now,
      decidedBy: "auto",
      auditLog: [...task.auditLog, { at: now, action: "auto-approved", note: "Non-sensitive task" }],
    };
  }
  const now = new Date().toISOString();
  return {
    ...task,
    status: "pending-approval",
    submittedAt: now,
    auditLog: [...task.auditLog, { at: now, action: "submitted-for-approval", by }],
  };
}

/** Approve a pending task. */
export function approve(task: AutomationTask, by: string): AutomationTask {
  const now = new Date().toISOString();
  return {
    ...task,
    status: "approved",
    decidedAt: now,
    decidedBy: by,
    auditLog: [...task.auditLog, { at: now, action: "approved", by }],
  };
}

/** Reject a pending task. */
export function reject(task: AutomationTask, by: string, note?: string): AutomationTask {
  const now = new Date().toISOString();
  return {
    ...task,
    status: "rejected",
    decidedAt: now,
    decidedBy: by,
    auditLog: [...task.auditLog, { at: now, action: "rejected", by, note }],
  };
}

/** Execute an approved task (export / send / apply). */
export function execute(task: AutomationTask, by: string): AutomationTask {
  if (task.status !== "approved") return task;
  const now = new Date().toISOString();
  return {
    ...task,
    status: "executed",
    executedAt: now,
    auditLog: [...task.auditLog, { at: now, action: "executed", by, note: "Task executed (exported/sent/applied)" }],
  };
}
