// Task Automation Agent
// =====================
// Generates draft operational tasks from the action plan + risk intelligence:
// daily manager briefing, opening/pre-peak/closing checklists, staff messages,
// supplier order drafts, incident reports, EOD summary, next-shift tasks.
// All sensitive tasks are created in "draft" state and require human approval
// before execution (per HUMAN_APPROVAL_POLICY).

import type { KfcStore } from "@/lib/stores/seed-stores";
import type { StoreOperatingProfile } from "@/lib/storeProfile/storeOperatingProfile";
import type { ActionPlan, SlotPlan, WeatherSignal, ManagerBriefing } from "@/lib/types";
import type { RiskIntelligenceResult } from "@/lib/operations/riskIntelligenceAgent";
import type { AnomalyAlert } from "@/lib/operations/realTimeEventSchema";
import {
  createTask,
  type AutomationTask,
} from "@/lib/automation/approvalWorkflow";

function todayDate(): string {
  return new Date().toLocaleDateString("en-GB", { timeZone: "Asia/Ho_Chi_Minh" });
}

function lunch(plan: ActionPlan): SlotPlan {
  return plan.slots[0];
}
function dinner(plan: ActionPlan): SlotPlan {
  return plan.slots[1];
}

/** Generate the full set of automation tasks for a store run. */
export function generateAutomationTasks(args: {
  store: KfcStore;
  profile: StoreOperatingProfile;
  plan: ActionPlan;
  briefing: ManagerBriefing;
  weather: WeatherSignal;
  risk: RiskIntelligenceResult;
}): AutomationTask[] {
  const { store, profile, plan, briefing, weather, risk } = args;
  const tasks: AutomationTask[] = [];
  const dataUsed = ["open-meteo", "store-operating-profile", "agent-action-plan", "realtime-ops-events"];

  // 1. Daily manager briefing (auto-approved — it's a draft).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "briefing",
      title: `Daily Manager Briefing — ${store.name}`,
      description: "30-second shift-ready summary generated by the Manager Briefing Agent.",
      content: [
        `# ${briefing.headline}`,
        "",
        "## TL;DR",
        ...briefing.tldr.map((t) => `- ${t}`),
        "",
        "## Top Actions",
        ...briefing.topActions.map((a, i) => `${i + 1}. ${a}`),
        "",
        "## Watch Items",
        ...briefing.watchItems.map((w) => `- ${w}`),
        "",
        `_${briefing.closingNote}_`,
      ].join("\n"),
      reason: "Manager requested a shift-ready briefing before opening.",
      dataUsed,
      confidence: plan.confidence,
      riskNote: "Low risk — internal document.",
    }),
  );

  // 2. Opening checklist (auto-approved).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "checklist",
      title: `Opening Checklist — ${store.name}`,
      description: "Pre-open checklist tailored to today's risk profile.",
      content: [
        `Opening Checklist — ${todayDate()} — ${store.name}`,
        "",
        `- [ ] Confirm weather signal: rain risk ${(weather.rainRiskScore * 100).toFixed(0)}%, walk-in drop ${(weather.walkInDropRisk * 100).toFixed(0)}%`,
        `- [ ] Prep philosophy today: ${profile.prepPhilosophy}`,
        `- [ ] Early batch size: ${lunch(plan).prepBatchDelta >= 0 ? "+" : ""}${lunch(plan).prepBatchDelta}% vs baseline`,
        `- [ ] Packaging buffer: +${Math.round(Math.max(0, Math.max(lunch(plan).expectedDeliveryDelta, dinner(plan).expectedDeliveryDelta)))}% delivery packaging`,
        `- [ ] Staff present vs scheduled (check staffing fit ${(risk.metrics.staffingFit * 100).toFixed(0)}%)`,
        `- [ ] Inventory floor confirmed (chicken, buckets, cups, bags)`,
        `- [ ] Campaign focus: ${plan.campaignRecommendation.split(".")[0]}`,
        `- [ ] ETA buffer set ${weather.deliveryDisruptionRisk > 0.5 ? "+10min" : "standard"}`,
        `- [ ] Waste log opened`,
      ].join("\n"),
      reason: "Standard opening procedure, adjusted for today's risk.",
      dataUsed,
      confidence: 0.85,
      riskNote: "Low risk — operational checklist.",
    }),
  );

  // 3. Pre-peak checklist (auto-approved).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "checklist",
      title: `Pre-Lunch Peak Checklist — ${store.name}`,
      description: "Checklist to run 30 min before lunch peak (11:00).",
      content: [
        `Pre-Lunch Peak Checklist — ${todayDate()}`,
        "",
        `- [ ] Fried chicken batch ready (reduced ${Math.abs(lunch(plan).prepBatchDelta)}% if rain)`,
        `- [ ] Delivery packaging pre-staged (+${Math.round(Math.max(0, lunch(plan).expectedDeliveryDelta))}%)`,
        `- [ ] Online-order packer assigned${lunch(plan).expectedDeliveryDelta > 12 ? " (1 dedicated)" : " (shared)"}`,
        `- [ ] Rider confirmation via aggregator${lunch(plan).expectedDeliveryDelta > 15 ? " (1 extra rider 11:00-13:30)" : ""}`,
        `- [ ] Sides (rice, coleslaw) at ${weather.rainRiskScore > 0.5 ? "80%" : "100%"} of peak`,
        `- [ ] App push notification scheduled 10:30`,
        `- [ ] ETA buffer ${weather.deliveryDisruptionRisk > 0.5 ? "+10min" : "standard"}`,
      ].join("\n"),
      reason: `Lunch peak is the highest-risk window for this ${profile.operatingType} store.`,
      dataUsed,
      confidence: 0.8,
      riskNote: "Low risk — operational checklist.",
    }),
  );

  // 4. Staff shift note (approval required to send).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "staff-message",
      title: `Lunch Shift Staff Note — ${store.name}`,
      description: "Draft message to lunch-shift staff (Zalo group).",
      content: [
        `📣 LUNCH SHIFT NOTE — ${todayDate()}`,
        "",
        `Team, today's lunch (${lunch(plan).windowLabel}):`,
        `- Walk-in ${lunch(plan).expectedWalkInDelta >= 0 ? "+" : ""}${lunch(plan).expectedWalkInDelta}%, delivery ${lunch(plan).expectedDeliveryDelta >= 0 ? "+" : ""}${lunch(plan).expectedDeliveryDelta}%`,
        `- ${lunch(plan).expectedDeliveryDelta > 12 ? "👉 1 dedicated online-order packer" : "👉 Shared packing"}`,
        `- ${lunch(plan).expectedWalkInDelta < -20 ? "👉 Walk-in drop expected — DON'T fry large batches early" : "👉 Standard batch cadence"}`,
        `- ${weather.deliveryDisruptionRisk > 0.5 ? "👉 Delivery ETA buffer +10min — tell customers" : ""}`,
        `- Campaign: ${plan.campaignRecommendation.split(".")[0]}`,
        "",
        "Let's have a smooth shift! 🍗",
      ].filter(Boolean).join("\n"),
      reason: "Staff need clear, weather-adjusted guidance before peak.",
      dataUsed,
      confidence: 0.78,
      riskNote: "Medium risk — sends a real message to staff. Manager must confirm wording.",
    }),
  );

  // 5. Supplier order draft (approval required).
  const inv = risk.events.find((e) => e.type === "inventory-level")?.payload;
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "supplier-order",
      title: `Supplier Order Draft — ${store.name}`,
      description: "Draft purchase order for replenishment (NOT sent until approved).",
      content: [
        `SUPPLIER ORDER DRAFT — ${todayDate()} — ${store.name}`,
        "",
        `Chicken raw: ${Number(inv?.chickenRawKg ?? 0) < store.kitchenCapacity * 5 ? `URGENT — order ${store.kitchenCapacity * 8}kg` : "sufficient"}`,
        `Buckets: ${Number(inv?.buckets ?? 0) < store.kitchenCapacity * 12 ? `URGENT — order ${store.kitchenCapacity * 20} units` : "sufficient"}`,
        `Cups: ${Number(inv?.cups ?? 0) < store.dineInSeats * 2 ? `order ${store.dineInSeats * 4} units` : "sufficient"}`,
        `Delivery bags: order ${Math.round(store.kitchenCapacity * (8 + weather.rainRiskScore * 6))} units (rain-adjusted)`,
        "",
        `Requested delivery: ${store.storeType === "suburban" ? "TODAY before 16:00 (long lead time)" : "tomorrow before 09:00"}`,
        `Reason: ${risk.metrics.stockoutProbability > 0.5 ? "stockout risk elevated" : "standard replenishment"}`,
        "",
        "⚠️ This is a DRAFT. No order is placed until the store manager approves.",
      ].join("\n"),
      reason: `Stockout probability ${(risk.metrics.stockoutProbability * 100).toFixed(0)}% — replenishment needed.`,
      dataUsed: [...dataUsed, "inventory-data"],
      confidence: 0.75,
      riskNote: "HIGH risk — commits a purchase order. Manager must approve.",
    }),
  );

  // 6. Incident report if there are critical alerts (auto-approved draft).
  const criticalAlerts = risk.alerts.filter((a) => a.severity === "critical");
  if (criticalAlerts.length > 0) {
    tasks.push(
      createTask({
        storeId: store.id,
        storeName: store.name,
        category: "incident-report",
        title: `Incident Report — ${store.name}`,
        description: "Auto-generated incident report for critical risk alerts.",
        content: [
          `INCIDENT REPORT — ${todayDate()} — ${store.name}`,
          "",
          `Generated: ${new Date().toISOString()}`,
          `Overall risk: ${(plan.overallRisk * 100).toFixed(0)}%`,
          "",
          "## Critical Alerts",
          ...criticalAlerts.map((a) => `- [${a.category.toUpperCase()}] ${a.title}: ${a.message} → ${a.recommendation}`),
          "",
          "## Action Taken",
          "- Plan adjusted (prep, staffing, campaign) per agent recommendation.",
          "- Draft tasks generated for staff message, supplier order, and campaign.",
          "- Manager notified.",
          "",
          "## Follow-up",
          "- Monitor metrics at next 15-min tick.",
          "- File this report in the shift log.",
        ].join("\n"),
        reason: `${criticalAlerts.length} critical alert(s) detected by Risk Intelligence Agent.`,
        dataUsed: [...dataUsed, "risk-intelligence-agent"],
        confidence: 0.8,
        riskNote: "Low risk — internal report. Sharing externally needs approval.",
      }),
    );
  }

  // 7. Campaign draft (approval required).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "campaign",
      title: `Campaign Draft — ${store.name}`,
      description: "Draft campaign push for today's risk window.",
      content: [
        `CAMPAIGN DRAFT — ${todayDate()} — ${store.name}`,
        "",
        `Focus: ${plan.campaignRecommendation.split(".")[0]}`,
        `Creative: ${weather.rainRiskScore > 0.55 ? "rainy-day cozy combo" : weather.heatRiskScore > 0.6 ? "chill combo" : "everyday value combo"}`,
        `Channel: ${weather.rainRiskScore > 0.5 && profile.operatingType !== "mall" ? "delivery app push + SMS" : profile.operatingType === "mall" ? "in-mall + dine-in" : "balanced"}`,
        `Timing: push 10:30 (lunch), 16:30 (dinner)`,
        `Budget cap: ${(weather.rainRiskScore > 0.5 ? 1.5 : 1).toFixed(1)}x baseline`,
        "",
        "⚠️ This is a DRAFT. No campaign launches until the area manager approves.",
      ].join("\n"),
      reason: "Campaign focus derived from rain/heat risk + store type.",
      dataUsed,
      confidence: 0.78,
      riskNote: "HIGH risk — launches a real campaign with spend + customer impact. Area manager must approve.",
    }),
  );

  // 8. End-of-day summary (auto-approved).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "end-of-day-summary",
      title: `End-of-Day Summary Template — ${store.name}`,
      description: "Template for the end-of-day summary (to be filled with actual results).",
      content: [
        `END-OF-DAY SUMMARY — ${todayDate()} — ${store.name}`,
        "",
        "## Plan vs Actual",
        `- Lunch walk-in forecast: ${lunch(plan).expectedWalkInDelta}% | Actual: ___`,
        `- Lunch delivery forecast: ${lunch(plan).expectedDeliveryDelta}% | Actual: ___`,
        `- Dinner walk-in forecast: ${dinner(plan).expectedWalkInDelta}% | Actual: ___`,
        `- Dinner delivery forecast: ${dinner(plan).expectedDeliveryDelta}% | Actual: ___`,
        "",
        "## Waste",
        `- Estimated waste risk: ${(risk.metrics.wasteTrend).toFixed(0)}% | Actual waste: ___`,
        "",
        "## Stockout",
        `- Stockout probability: ${(risk.metrics.stockoutProbability * 100).toFixed(0)}% | Actual stockouts: ___`,
        "",
        "## Staffing",
        `- Staffing fit: ${(risk.metrics.staffingFit * 100).toFixed(0)}% | Notes: ___`,
        "",
        "## Complaints",
        `- Complaint risk: ${(risk.metrics.complaintRisk * 100).toFixed(0)}% | Actual complaints: ___`,
        "",
        "## Learnings for next run",
        "- ___",
      ].join("\n"),
      reason: "Capture actual results vs forecast for the Learn phase of the agent loop.",
      dataUsed,
      confidence: 0.7,
      riskNote: "Low risk — internal template.",
    }),
  );

  // 9. Next-shift task (auto-approved).
  tasks.push(
    createTask({
      storeId: store.id,
      storeName: store.name,
      category: "checklist",
      title: `Next-Shift Prep Task — ${store.name}`,
      description: "Specific tasks for the next shift based on today's risk.",
      content: [
        `NEXT-SHIFT TASKS — ${todayDate()}`,
        "",
        profile.operatingType === "urban-center"
          ? `- Do NOT fry large batch before 10:45 (walk-in drop risk ${(weather.walkInDropRisk * 100).toFixed(0)}%)`
          : "",
        `- Prepare ${Math.round(Math.max(0, dinner(plan).expectedDeliveryDelta))}% extra delivery packaging for dinner`,
        risk.metrics.stockoutProbability > 0.5 ? `- URGENT: check ${store.storeType === "suburban" ? "spicy chicken" : "family bucket"} stock before 17:00` : "",
        `- Confirm dinner staffing: ${dinner(plan).staffingDelta >= 0 ? "+" : ""}${dinner(plan).staffingDelta} vs baseline`,
        weather.heatRiskScore > 0.6 ? `- Stock ice & cold beverages (+${Math.round(weather.heatRiskScore * 20)}%)` : "",
      ].filter(Boolean).join("\n"),
      reason: "Hand off concrete tasks to the next shift based on risk.",
      dataUsed,
      confidence: 0.78,
      riskNote: "Low risk — operational tasks.",
    }),
  );

  return tasks;
}

/** Group tasks by status for the UI. */
export function groupByStatus(tasks: AutomationTask[]): Record<string, AutomationTask[]> {
  const groups: Record<string, AutomationTask[]> = {
    draft: [],
    "pending-approval": [],
    approved: [],
    rejected: [],
    executed: [],
  };
  for (const t of tasks) {
    if (!groups[t.status]) groups[t.status] = [];
    groups[t.status].push(t);
  }
  return groups;
}

/** Group tasks by category for the UI. */
export function groupByCategory(tasks: AutomationTask[]): Record<string, AutomationTask[]> {
  const groups: Record<string, AutomationTask[]> = {};
  for (const t of tasks) {
    if (!groups[t.category]) groups[t.category] = [];
    groups[t.category].push(t);
  }
  return groups;
}

/** Convert alerts to automation triggers (for the trace). */
export function alertsToTriggers(alerts: AnomalyAlert[]): string[] {
  return alerts.map((a) => `[${a.severity}] ${a.category}: ${a.title}`);
}
