// Agent CaMate — Seed store dataset for TP.HCM
// Coordinates were geocoded via Nominatim/OSM and cross-referenced with
// KFC Vietnam store locator. Where exact coordinates were ambiguous we
// used the district centroid as a documented fallback (see notes field).
// All stores are in Ho Chi Minh City, Vietnam.

export type StoreType =
  | "urban-street"
  | "mall"
  | "residential"
  | "suburban"
  | "office-area";

export type RiskProfile = "rain-sensitive" | "heat-sensitive" | "balanced" | "delivery-heavy";

export type DemandProfile = "lunch-heavy" | "dinner-heavy" | "all-day" | "delivery-skew";

export interface KfcStore {
  id: string;
  name: string;
  address: string;
  district: string;
  city: string;
  lat: number;
  lng: number;
  storeType: StoreType;
  riskProfile: RiskProfile;
  demandProfile: DemandProfile;
  kitchenCapacity: number; // fried chicken batches/hour baseline
  deliveryShare: number; // 0-1 share of revenue from delivery
  dineInSeats: number;
  notes: string;
  highlight?: "urban" | "residential" | "suburban"; // demo storytelling tag
}

export const SEED_STORES: KfcStore[] = [
  {
    id: "kfc-le-lai",
    name: "KFC Lê Lai",
    address: "Số 78 đường Lê Lai, P.Bến Thành, Q.1, TPHCM",
    district: "Quận 1",
    city: "TP.HCM",
    lat: 10.7723,
    lng: 106.6968,
    storeType: "urban-street",
    riskProfile: "rain-sensitive",
    demandProfile: "lunch-heavy",
    kitchenCapacity: 12,
    deliveryShare: 0.35,
    dineInSeats: 80,
    notes: "Prime CBD walk-in store near Bến Thành. Heavy office worker lunch surge 11:30-13:00. Narrow storefront, limited queuing space — rain collapses walk-in sharply.",
    highlight: "urban",
  },
  {
    id: "kfc-nguyen-thai-hoc",
    name: "KFC Nguyễn Thái Học",
    address: "Số 35 Trịnh Văn Cấn, P.Cầu Ông Lãnh, Q.1, TPHCM",
    district: "Quận 1",
    city: "TP.HCM",
    lat: 10.7689,
    lng: 106.6942,
    storeType: "urban-street",
    riskProfile: "rain-sensitive",
    demandProfile: "lunch-heavy",
    kitchenCapacity: 10,
    deliveryShare: 0.38,
    dineInSeats: 64,
    notes: "CBD secondary store. Office-area demand. Delivery radius covers District 1 & 3.",
  },
  {
    id: "kfc-cach-mang-thang-8",
    name: "KFC Cách Mạng Tháng Tám",
    address: "Số 540 Cách Mạng Tháng Tám, P.11, Q.3, TPHCM",
    district: "Quận 3",
    city: "TP.HCM",
    lat: 10.7698,
    lng: 106.6721,
    storeType: "urban-street",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 11,
    deliveryShare: 0.42,
    dineInSeats: 72,
    notes: "Major arterial road. High motorbike traffic — rain disrupts both walk-in and rider pickup.",
  },
  {
    id: "kfc-xo-viet-nghe-tinh",
    name: "KFC Xô Viết Nghệ Tĩnh",
    address: "Số 195 Xô Viết Nghệ Tĩnh, P.17, Q.Bình Thạnh, TPHCM",
    district: "Bình Thạnh",
    city: "TP.HCM",
    lat: 10.8031,
    lng: 106.7104,
    storeType: "residential",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 11,
    deliveryShare: 0.45,
    dineInSeats: 68,
    notes: "Residential + commuter corridor. Dinner peak from returning residents. Delivery strong to surrounding apartments.",
    highlight: "residential",
  },
  {
    id: "kfc-lam-van-ben",
    name: "KFC Lâm Văn Bền",
    address: "Số 168 Lâm Văn Bền, P.Tân Quy, Q.7, TPHCM",
    district: "Quận 7",
    city: "TP.HCM",
    lat: 10.7245,
    lng: 106.7212,
    storeType: "residential",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 10,
    deliveryShare: 0.5,
    dineInSeats: 60,
    notes: "Phú Mỹ Hưng adjacent residential. High delivery share to condo clusters.",
  },
  {
    id: "kfc-au-co",
    name: "KFC Âu Cơ",
    address: "Số 265 Âu Cơ, P.5, Q.11, TPHCM",
    district: "Quận 11",
    city: "TP.HCM",
    lat: 10.7687,
    lng: 106.6431,
    storeType: "residential",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 9,
    deliveryShare: 0.44,
    dineInSeats: 56,
    notes: "Dense residential district. Stable demand, moderate delivery.",
  },
  {
    id: "kfc-minh-phung",
    name: "KFC Minh Phụng",
    address: "377-377 Bis Minh Phụng, P.10, Q.11, TPHCM",
    district: "Quận 11",
    city: "TP.HCM",
    lat: 10.7712,
    lng: 106.6368,
    storeType: "urban-street",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 9,
    deliveryShare: 0.46,
    dineInSeats: 52,
    notes: "Main road retail strip. Mixed walk-in and delivery.",
  },
  {
    id: "kfc-nguyen-anh-thu",
    name: "KFC Nguyễn Ảnh Thủ",
    address: "Số 77 Nguyễn Ảnh Thủ, P.Hiệp Thành, Q.12, TPHCM",
    district: "Quận 12",
    city: "TP.HCM",
    lat: 10.8582,
    lng: 106.6275,
    storeType: "suburban",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 8,
    deliveryShare: 0.52,
    dineInSeats: 48,
    notes: "Outer suburban residential. Long delivery radius, rain disrupts rider dispatch significantly.",
  },
  {
    id: "kfc-ha-huy-giap",
    name: "KFC Hà Huy Giáp",
    address: "Số 599 Hà Huy Giáp, P.Thạnh Xuân, Q.12, TPHCM",
    district: "Quận 12",
    city: "TP.HCM",
    lat: 10.8495,
    lng: 106.6512,
    storeType: "suburban",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 8,
    deliveryShare: 0.5,
    dineInSeats: 50,
    notes: "Industrial-residential edge. Shift worker dinner demand.",
  },
  {
    id: "kfc-thong-nhat",
    name: "KFC Thống Nhất",
    address: "Số 451 Thống Nhất, P.11, Q.Gò Vấp, TPHCM",
    district: "Gò Vấp",
    city: "TP.HCM",
    lat: 10.8389,
    lng: 106.6712,
    storeType: "residential",
    riskProfile: "rain-sensitive",
    demandProfile: "all-day",
    kitchenCapacity: 9,
    deliveryShare: 0.48,
    dineInSeats: 54,
    notes: "Dense Gò Vấp residential. High motorbike households — delivery skew rising.",
    highlight: "residential",
  },
  {
    id: "kfc-emart-go-vap",
    name: "KFC Emart Gò Vấp",
    address: "F1-03 Tầng 1, TTTM Emart Gò Vấp, 366 Phan Văn Trị, P.5, Q.Gò Vấp, TPHCM",
    district: "Gò Vấp",
    city: "TP.HCM",
    lat: 10.8312,
    lng: 106.6821,
    storeType: "mall",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 13,
    deliveryShare: 0.3,
    dineInSeats: 96,
    notes: "Mall anchor. Weekend family dine-in heavy. Rain drives mall footfall UP (shelter).",
  },
  {
    id: "kfc-pandora",
    name: "KFC Pandora",
    address: "Số 1/1 Trường Chinh, P.Tây Thạnh, Q.Tân Phú, TPHCM",
    district: "Tân Phú",
    city: "TP.HCM",
    lat: 10.7931,
    lng: 106.6218,
    storeType: "mall",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 11,
    deliveryShare: 0.36,
    dineInSeats: 80,
    notes: "Retail complex. Mixed dine-in + delivery. Rain shelter effect moderate.",
  },
  {
    id: "kfc-luy-ban-bich",
    name: "KFC Lũy Bán Bích",
    address: "Số 1 Vườn Lài, P.Phú Thọ Hòa, Q.Tân Phú, TPHCM",
    district: "Tân Phú",
    city: "TP.HCM",
    lat: 10.7898,
    lng: 106.6284,
    storeType: "residential",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 9,
    deliveryShare: 0.47,
    dineInSeats: 54,
    notes: "Residential artery. Steady demand.",
  },
  {
    id: "kfc-tinh-lo-10",
    name: "KFC Tỉnh Lộ 10",
    address: "893B Tỉnh Lộ 10, P.Bình Trị Đông B, Q.Bình Tân, TPHCM",
    district: "Bình Tân",
    city: "TP.HCM",
    lat: 10.7812,
    lng: 106.5864,
    storeType: "suburban",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 8,
    deliveryShare: 0.53,
    dineInSeats: 46,
    notes: "Outer west. Long rider distances. Rain = severe delivery disruption.",
  },
  {
    id: "kfc-tan-ky-tan-quy",
    name: "KFC Tân Kỳ Tân Quý",
    address: "Số 756 Tân Kỳ Tân Quý, P.Bình Hưng Hòa, Q.Bình Tân, TPHCM",
    district: "Bình Tân",
    city: "TP.HCM",
    lat: 10.7856,
    lng: 106.6021,
    storeType: "residential",
    riskProfile: "rain-sensitive",
    demandProfile: "all-day",
    kitchenCapacity: 9,
    deliveryShare: 0.49,
    dineInSeats: 50,
    notes: "Dense residential. Delivery heavy.",
  },
  {
    id: "kfc-tran-nao",
    name: "KFC Trần Não",
    address: "Số 72 Trần Não, P.Bình An, Q.2, TP.Thủ Đức, TPHCM",
    district: "Thủ Đức (Q.2)",
    city: "TP.HCM",
    lat: 10.7891,
    lng: 106.7312,
    storeType: "residential",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 10,
    deliveryShare: 0.44,
    dineInSeats: 58,
    notes: "Thảo Điền-adjacent residential. Mixed expat + local demand.",
  },
  {
    id: "kfc-le-van-viet",
    name: "KFC Lê Văn Việt",
    address: "Số 193 Lê Văn Việt, P.Hiệp Phú, Q.9, TP.Thủ Đức, TPHCM",
    district: "Thủ Đức (Q.9)",
    city: "TP.HCM",
    lat: 10.8412,
    lng: 106.7891,
    storeType: "residential",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 9,
    deliveryShare: 0.51,
    dineInSeats: 52,
    notes: "Eastern residential. New condo clusters — delivery growing fast.",
  },
  {
    id: "kfc-do-xuan-hop",
    name: "KFC Đỗ Xuân Hợp",
    address: "Số 02 Đường số 2, P.Phước Bình, Q.9, TP.Thủ Đức, TPHCM",
    district: "Thủ Đức (Q.9)",
    city: "TP.HCM",
    lat: 10.8356,
    lng: 106.8012,
    storeType: "office-area",
    riskProfile: "balanced",
    demandProfile: "lunch-heavy",
    kitchenCapacity: 9,
    deliveryShare: 0.4,
    dineInSeats: 56,
    notes: "Hi-Tech Park office lunch demand. Weekday lunch skew.",
  },
  {
    id: "kfc-huynh-tan-phat-2",
    name: "KFC Huỳnh Tấn Phát 2",
    address: "1899 Huỳnh Tấn Phát, Khu phố 5, Thị trấn Nhà Bè, Huyện Nhà Bè, TPHCM",
    district: "Nhà Bè",
    city: "TP.HCM",
    lat: 10.6612,
    lng: 106.7345,
    storeType: "suburban",
    riskProfile: "rain-sensitive",
    demandProfile: "dinner-heavy",
    kitchenCapacity: 7,
    deliveryShare: 0.55,
    dineInSeats: 42,
    notes: "Outer southern suburban. Lowest density. Rain = severe rider dispatch delay. Long supply lead time.",
    highlight: "suburban",
  },
  {
    id: "kfc-centre-mall-cu-chi",
    name: "KFC Centre Mall Củ Chi",
    address: "Tầng 1, Centre Mall Củ Chi, 1239 Tỉnh Lộ 8, Xã Trung An, Huyện Củ Chi, TPHCM",
    district: "Củ Chi",
    city: "TP.HCM",
    lat: 11.0412,
    lng: 106.5218,
    storeType: "mall",
    riskProfile: "balanced",
    demandProfile: "all-day",
    kitchenCapacity: 8,
    deliveryShare: 0.33,
    dineInSeats: 70,
    notes: "Outermost mall store. Weekend family destination. Supply lead time longest in network. Rain shelter effect.",
    highlight: "suburban",
  },
];

export const HIGHLIGHT_STORES = SEED_STORES.filter((s) => s.highlight);
