import { NextResponse } from "next/server";
import { requirePkfcApiKey } from "@/lib/pkfc/auth";
import { db } from "@/lib/db";
import type { AgentRunResult } from "@/lib/types";

export const dynamic = "force-dynamic";

function deriveOpsModeFromTrace(trace: any[]): "live" | "csv" | "simulated" | "none" {
  const opsTrace = trace.find((t) => t.agentName === "Operations Baseline Agent");
  if (opsTrace) {
    const out = (opsTrace.output || "").toLowerCase();
    if (out.includes("sponsor(ok)") || out.includes("live")) return "live";
    if (out.includes("csv(ok)") || out.includes("csv")) return "csv";
    if (out.includes("synthetic")) return "simulated";
  }
  return "none";
}

function reconstructRun(run: {
  storeId: string;
  storeName: string;
  traceJson: string;
  planJson: string;
  briefingJson: string;
  isLive: boolean;
  triggeredAt: Date;
}): AgentRunResult & { opsBaselineMode?: string; dataSources?: any } {
  const trace = JSON.parse(run.traceJson);
  const plan = JSON.parse(run.planJson);
  return {
    storeId: run.storeId,
    storeName: run.storeName,
    trace,
    plan,
    briefing: JSON.parse(run.briefingJson),
    beforeAfter: [],
    weather: trace[1]?.structuredOutput?.signal ?? trace.find((t: { agentName: string }) => t.agentName === "Weather Signal Agent")?.structuredOutput ?? {},
    weatherProvenance: {
      primarySource: "open-meteo",
      primaryMode: run.isLive ? "live" : "fallback",
      contributors: [],
    },
    isLive: run.isLive,
    generatedAt: run.triggeredAt.toISOString(),
    totalDurationMs: 0,
    opsBaselineMode: plan.opsBaselineMode ?? deriveOpsModeFromTrace(trace),
    dataSources: plan.dataSources,
  };
}

function buildBriefingMarkdown(result: AgentRunResult): string {
  const { briefing, plan, weather, trace } = result;
  const lines: string[] = [];
  lines.push(`# Manager Briefing — ${briefing.storeName}`);
  lines.push("");
  lines.push(`**Generated:** ${new Date(briefing.generatedAt).toLocaleString("en-GB", { timeZone: "Asia/Ho_Chi_Minh" })} (ICT)`);
  lines.push(`**Planning date:** ${plan.planningDate}`);
  lines.push(`**Data source:** ${weather.isLive ? "LIVE (Open-Meteo)" : "FALLBACK"} — ${weather.source}`);
  lines.push(`**Confidence:** ${(plan.confidence * 100).toFixed(0)}% (${briefing.confidenceLabel})`);
  lines.push(`**Overall operational risk:** ${(plan.overallRisk * 100).toFixed(0)}%`);
  lines.push("");
  lines.push("## Headline");
  lines.push(briefing.headline);
  lines.push("");
  lines.push("## TL;DR");
  briefing.tldr.forEach((t) => lines.push(`- ${t}`));
  lines.push("");
  lines.push("## Top Actions");
  briefing.topActions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
  lines.push("");
  lines.push("## Watch Items");
  briefing.watchItems.forEach((w) => lines.push(`- ${w}`));
  lines.push("");
  lines.push("## Store Risk Summary");
  lines.push(plan.storeRiskSummary);
  lines.push("");
  lines.push("## Slot Plan");
  plan.slots.forEach((s) => {
    lines.push(`### ${s.slot.toUpperCase()} — ${s.windowLabel}`);
    lines.push(`- Walk-in delta: ${s.expectedWalkInDelta >= 0 ? "+" : ""}${s.expectedWalkInDelta}%`);
    lines.push(`- Delivery delta: ${s.expectedDeliveryDelta >= 0 ? "+" : ""}${s.expectedDeliveryDelta}%`);
    lines.push(`- Prep batch delta: ${s.prepBatchDelta >= 0 ? "+" : ""}${s.prepBatchDelta}%`);
    lines.push(`- Staffing delta: ${s.staffingDelta >= 0 ? "+" : ""}${s.staffingDelta}`);
    lines.push(`- Packaging delta: ${s.packagingDelta >= 0 ? "+" : ""}${s.packagingDelta}%`);
    if (s.warnings.length) lines.push(`- Warnings: ${s.warnings.join("; ")}`);
    lines.push("");
  });
  lines.push("## Inventory");
  lines.push(plan.inventoryRecommendation);
  lines.push("");
  lines.push("## Prep");
  lines.push(plan.prepRecommendation);
  lines.push("");
  lines.push("## Staffing");
  lines.push(plan.staffingRecommendation);
  lines.push("");
  lines.push("## Delivery Readiness");
  lines.push(plan.deliveryReadiness);
  lines.push("");
  lines.push("## Campaign");
  lines.push(plan.campaignRecommendation);
  lines.push("");
  lines.push("---");
  lines.push("_Generated by Agent CaMate — P-KFC API. Independent hackathon demo. Not an official KFC product._");
  return lines.join("\n");
}

export async function POST(req: Request) {
  const auth = requirePkfcApiKey(req);
  if (!auth.ok && auth.errorResponse) {
    return auth.errorResponse;
  }

  let body: { runId?: string; language?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({
      ok: false,
      error: "invalid_body",
      message: "Invalid JSON body."
    }, { status: 400 });
  }

  const { runId, language = "vi" } = body;
  if (!runId) {
    return NextResponse.json({
      ok: false,
      error: "missing_runId",
      message: "runId is required."
    }, { status: 400 });
  }

  try {
    const run = await db.agentRun.findUnique({ where: { id: runId } });
    if (!run) {
      return NextResponse.json({
        ok: false,
        error: "run_not_found",
        message: `Run with ID '${runId}' not found.`
      }, { status: 404 });
    }

    const reconstructed = reconstructRun(run);
    const markdown = buildBriefingMarkdown(reconstructed);
    const safeName = run.storeName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
    const date = new Date().toISOString().slice(0, 10);
    const filename = `briefing-${safeName}-${date}.md`;

    return NextResponse.json({
      ok: true,
      markdown,
      filename,
      disclaimer: "Independent hackathon demo. Not an official KFC product."
    });
  } catch (err: any) {
    return NextResponse.json({
      ok: false,
      error: "error",
      message: `Failed to export briefing: ${err.message || err}`
    }, { status: 500 });
  }
}
