// POST /api/briefing/export — export a manager briefing as downloadable text/markdown
// Body: { result: AgentRunResult }
import { NextResponse } from "next/server";
import type { AgentRunResult } from "@/lib/types";

function buildMarkdown(result: AgentRunResult): string {
  const { briefing, plan, weather, trace } = result;
  const lines: string[] = [];
  lines.push(`# Manager Briefing — ${briefing.storeName}`);
  lines.push("");
  lines.push(`**Generated:** ${new Date(briefing.generatedAt).toLocaleString("en-GB", { timeZone: "Asia/Ho_Chi_Minh" })} (ICT)`);
  lines.push(`**Planning date:** ${plan.planningDate}`);
  lines.push(`**Data source:** ${weather.isLive ? "LIVE (Open-Meteo)" : "FALLBACK"} — ${weather.source}`);
  lines.push(`**Confidence:** ${(plan.confidence * 100).toFixed(0)}% (${briefing.confidenceLabel})`);
  lines.push(`**Overall operational risk:** ${(plan.overallRisk * 100).toFixed(0)}%`);
  lines.push("");
  lines.push("## Headline");
  lines.push(briefing.headline);
  lines.push("");
  lines.push("## TL;DR");
  briefing.tldr.forEach((t) => lines.push(`- ${t}`));
  lines.push("");
  lines.push("## Top Actions");
  briefing.topActions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
  lines.push("");
  lines.push("## Watch Items");
  briefing.watchItems.forEach((w) => lines.push(`- ${w}`));
  lines.push("");
  lines.push("## Store Risk Summary");
  lines.push(plan.storeRiskSummary);
  lines.push("");
  lines.push("## Slot Plan");
  plan.slots.forEach((s) => {
    lines.push(`### ${s.slot.toUpperCase()} — ${s.windowLabel}`);
    lines.push(`- Walk-in delta: ${s.expectedWalkInDelta >= 0 ? "+" : ""}${s.expectedWalkInDelta}%`);
    lines.push(`- Delivery delta: ${s.expectedDeliveryDelta >= 0 ? "+" : ""}${s.expectedDeliveryDelta}%`);
    lines.push(`- Prep batch delta: ${s.prepBatchDelta >= 0 ? "+" : ""}${s.prepBatchDelta}%`);
    lines.push(`- Staffing delta: ${s.staffingDelta >= 0 ? "+" : ""}${s.staffingDelta}`);
    lines.push(`- Packaging delta: ${s.packagingDelta >= 0 ? "+" : ""}${s.packagingDelta}%`);
    if (s.warnings.length) lines.push(`- Warnings: ${s.warnings.join("; ")}`);
    lines.push("");
  });
  lines.push("## Inventory");
  lines.push(plan.inventoryRecommendation);
  lines.push("");
  lines.push("## Prep");
  lines.push(plan.prepRecommendation);
  lines.push("");
  lines.push("## Staffing");
  lines.push(plan.staffingRecommendation);
  lines.push("");
  lines.push("## Delivery Readiness");
  lines.push(plan.deliveryReadiness);
  lines.push("");
  lines.push("## Campaign");
  lines.push(plan.campaignRecommendation);
  lines.push("");
  if (plan.wasteWarnings.length) {
    lines.push("## Waste Warnings");
    plan.wasteWarnings.forEach((w) => lines.push(`- ${w}`));
    lines.push("");
  }
  if (plan.stockoutWarnings.length) {
    lines.push("## Stockout Warnings");
    plan.stockoutWarnings.forEach((w) => lines.push(`- ${w}`));
    lines.push("");
  }
  if (plan.serviceDelayWarnings.length) {
    lines.push("## Service Delay Warnings");
    plan.serviceDelayWarnings.forEach((w) => lines.push(`- ${w}`));
    lines.push("");
  }
  lines.push("## Risk Factors (ranked)");
  plan.risks.forEach((r, i) => {
    lines.push(`${i + 1}. **${r.factor}** (weight ${r.weight.toFixed(2)}) — ${r.reasoning}`);
  });
  lines.push("");
  lines.push("## Agent Execution Trace");
  trace.forEach((t) => {
    lines.push(`### Step ${t.step} — ${t.agentName} [${t.phase}]`);
    lines.push(`- Confidence: ${(t.confidence * 100).toFixed(0)}%`);
    lines.push(`- Data source: ${t.dataSource}`);
    lines.push(`- Timestamp: ${new Date(t.timestamp).toLocaleString("en-GB", { timeZone: "Asia/Ho_Chi_Minh" })}`);
    lines.push(`- Duration: ${t.durationMs}ms`);
    lines.push(`- Input: ${t.input}`);
    lines.push(`- Output: ${t.output}`);
    lines.push("");
  });
  lines.push("---");
  lines.push("_Generated by Agent CaMate — Agentic AI Build Week 2026 demo. Not an official KFC product._");
  return lines.join("\n");
}

export async function POST(req: Request) {
  let body: { result?: AgentRunResult };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }
  if (!body.result) {
    return NextResponse.json({ error: "result is required" }, { status: 400 });
  }
  const md = buildMarkdown(body.result);
  const safeName = body.result.briefing.storeName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const date = new Date().toISOString().slice(0, 10);
  return new NextResponse(md, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="briefing-${safeName}-${date}.md"`,
    },
  });
}
